### ISSUE TITLE
Better language support.

### ISSUE THREAD

**Issue by saibotsivad** [tobiaslabs/json-schema-to-markdown#1]
It would be nice to have better language support, e.g. instead of writing it as

```js
text.push('Properties of the `' + subSchemaTypeName + '` object:')
```

you'd have something like either a function or string replace `%s` type stuff so people could pass in their own word object.

Doing that would give you multi-language support, which is always neat.

**Comment by kruncher** [comment]
The [format-unicorn](https://www.npmjs.com/package/format-unicorn) package might be useful in this scenario:

**strings/en.js**
```javascript
module.exports = {
  // name: name of the sub schema
  "object.properties.heading": "Properties of the `{name}` object:"
};
```

**Usage Example**
```javascript
var formatUnicorn = require("format-unicorn/safe");
var strings = require("./strings/en");

text.push(formatUnicorn(strings["object.properties.heading"], { name: subSchemaTypeName }));
```

**Comment by saibotsivad** [comment]
I've thought about this a bit, and I don't think this is within the scope of this project.

The goal of this module is `JSON Schema => Markdown` and adding language support seems like a different problem to me.

I'll still need to tackle language support where I use this module, but what I imagine is that a person would have a schema like `schema.json` and some language files like `lang-eng-us.json` and `lang-zch.json`, and use *some other module* to generate `schema-eng-us.json` and `schema-zch.json`, and run *those* files through this module.

With that said, I'll close this issue until someone brings up an objection.
