### ISSUE TITLE
When is the npm package going to be updated?

### ISSUE THREAD

**Issue by kruncher** [tobiaslabs/json-schema-to-markdown#7]
Hi,

At the moment I am still using the git repository as my npm dependency instead of the npm package `json-schema-to-markdown`. Any thoughts on when the npm package update will be published?

Many thanks

**Comment by saibotsivad** [comment]
Wow, I didn't realize I hadn't pushed out a new version to npm after your pull request got landed. Sorry about that!

I just merged in some other fixes with #6 and pushed all that out to npm.

Thanks!

**Comment by kruncher** [comment]
Not a problem! thanks for pushing the package! :)
